### ISSUE TITLE
Using directory with name "api" conflicts with internal API server

### ISSUE THREAD

**Issue by ammmir** [markdoc/markdoc#199]
### What happened?

If you have a directory under pages called `api` it won't render as it apparently conflicts with the internal DevServer.

```
error - TypeError: Cannot read properties of undefined (reading 'content')
    at MarkdocComponent (webpack-internal:///./pages/api/index.md:85:88)
    at Object.apiResolver (/Users/amir/x/markdoc-starter/node_modules/next/dist/server/api-utils/node.js:366:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runApi (/Users/amir/x/markdoc-starter/node_modules/next/dist/server/next-server.js:469:9)
    at async Object.fn (/Users/amir/x/markdoc-starter/node_modules/next/dist/server/next-server.js:719:37)
    at async Router.execute (/Users/amir/x/markdoc-starter/node_modules/next/dist/server/router.js:247:36)
    at async DevServer.run (/Users/amir/x/markdoc-starter/node_modules/next/dist/server/base-server.js:346:29)
    at async DevServer.run (/Users/amir/x/markdoc-starter/node_modules/next/dist/server/dev/next-dev-server.js:708:20)
    at async DevServer.handleRequest (/Users/amir/x/markdoc-starter/node_modules/next/dist/server/base-server.js:284:20) {
  page: '/api'
}
  82 | export default function MarkdocComponent(props) {
  83 |   // Only execute HMR code in development
> 84 |   return renderers.react(props.markdoc.content, React, {
     |                                       ^
  85 |     components: {
  86 |       ...components,
  87 |       // Allows users to override default components at runtime, via their _app
```

### To reproduce

```shell
git clone https://github.com/markdoc/markdoc-starter.git
cd markdoc-starter
npm i
mv pages/docs pages/api
npm run dev
```

Then open http://localhost:3000/api and you'll be greeted with the error.

### Version

latest

**Comment by mfix-stripe** [comment]
@ammmir can you share the code that reproduces this? This might be an issue with how your `_app.js` is set up.

**Comment by ijjk** [comment]
There isn't currently a way to disable the `api` directory handling, a workaround can be to name the file something else and rewrite to it instead though.

**Comment by ammmir** [comment]
@mfix-stripe i'm using the stock https://github.com/markdoc/markdoc-starter/blob/main/pages/_app.tsx but it seems to be a next.js limitation/design choice so i will use a workaround. thanks!
