### ISSUE TITLE
Lists with tags with async tranforms fail

### ISSUE THREAD

**Issue by arranf** [markdoc/markdoc#256]
### What happened?

A basic list with a an async transformed tag (for data fetching) throws the following error

```
TypeError: children.map is not a function
    at render3 (/home/arranf/valinde-rpg/node_modules/@markdoc/markdoc/dist/index.js:7934:131)
    at Array.map (<anonymous>)
    at render3 (/home/arranf/valinde-rpg/node_modules/@markdoc/markdoc/dist/index.js:7934:131)
    at Object.dynamic [as react] (/home/arranf/valinde-rpg/node_modules/@markdoc/markdoc/dist/index.js:7936:10)
    at MarkdocComponent (webpack-internal:///./src/pages/codex/creating-your-character/paths/test.md:84:68)
    at renderWithHooks (/home/arranf/valinde-rpg/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/arranf/valinde-rpg/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/home/arranf/valinde-rpg/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/arranf/valinde-rpg/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/arranf/valinde-rpg/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)

```

### To reproduce

1. Create a file with a list and async tag e.g.

```
* foo bar {% my-async-tag bar="baz %}hello world{% /my-async-tag %}. More lorem ipsum.
* foo bar
```

```
export const myAsyncTag = {
  render: MyComponent,
  description: "Demo",
  attributes: {
    bar: {
      type: String,
      errorLevel: "critical",
      description: "Some important information",
    },
  },
  transform: async (node, config) => {
    const attributes = node.transformAttributes(config);
    const children = node.transformChildren(config);
    console.log(children);
    return new Tag("span", attributes, children);
  },
};
```

Removing the `async` keyword this renders correctly. Note that _with_ the `async` keyword the children is logged _after_ the error is thrown.

### Version

    "@markdoc/markdoc": "^0.1.13",     "@markdoc/next.js": "^0.1.11-0",

### Additional context

Using nextjs for rendering.

**Comment by mfix-stripe** [comment]
@arranf are you using `@markdoc/next.js`? Async transforms are still experimental, and have not been enabled in the `@markdoc/next.js` Next.js plugin. If you are using it separately from `@markdoc/next.js`, you might need to `await` somewhere within your stack.

**Comment by mfix-stripe** [comment]
Gonna close this as async transforms are still experimental, but please let me know if this doesn't full capture the issue you are facing, and I will re-open. Appreciate your involvement in the project @arranf! 🙂
