### ISSUE TITLE
Website  using markdoc getting crash randomly  with TypeError: Cannot read properties of undefined (reading 'content')

### ISSUE THREAD

**Issue by Yashaswi-1998** [markdoc/markdoc#485]
### What happened?

Sometimes on opening the page of the website for the first time, it throws a client-side error with the below logs in the browser console. On refreshing the page everything starts working normally and the issue never reproduces.
```
main-cd810e1dc0d18097.js:1 TypeError: Cannot read properties of undefined (reading 'content')
    at MarkdocComponent (file-upload-widget-using-uppy-5d409c8236e38554.js:1:569)
    at Xh (framework-ca706bf673a13738.js:9:60992)
    at x (framework-ca706bf673a13738.js:9:119447)
    at Vk (framework-ca706bf673a13738.js:9:99132)
    at framework-ca706bf673a13738.js:9:98999
    at Jk (framework-ca706bf673a13738.js:9:99006)
    at Ok (framework-ca706bf673a13738.js:9:95762)
    at Hk (framework-ca706bf673a13738.js:9:94318)
    at J (framework-ca706bf673a13738.js:33:1364)
    at MessagePort.R (framework-ca706bf673a13738.js:33:1894)
```

Below I am pasting the file-upload-widget-using-uppy-5d409c8236e38554.js code which i copied from the browser by going through the first stack trace. This all is internal code not written by me.

```
(self.webpackChunk_N_E = self.webpackChunk_N_E || []).push([[8864], {
    92338: function(n, t, o) {
        (window.__NEXT_P = window.__NEXT_P || []).push(["/integration/file-upload-widget", function() {
            return o(10778)
        }
        ])
    },
    10778: function(n, t, o) {
        "use strict";
        o.r(t),
        o.d(t, {
            __N_SSG: function() {
                return s
            },
            default: function() {
                return MarkdocComponent
            }
        });
        var e = o(67294)
          , u = o(4211)
          , c = o(84266)
          , r = o(41093)
          , i = o(64790)
          , _ = o(68008);
        let f = {
            tags: (0,
            c.w)(r),
            nodes: (0,
            c.w)(i),
            functions: (0,
            c.w)(_),
            ...(0,
            c.w)({})
        }
          , {components: a} = (0,
        c.J)(f);
        var s = !0;
        function MarkdocComponent(n) {
            return u.RZ.react(n.markdoc.content, e, {. // **this is line where it is reading content of undefined**
                components: {
                    ...a,
                    ...n.components
                }
            })
        }
    }
}, function(n) {
    n.O(0, [7933, 9774, 2888, 179], function() {
        return n(n.s = 92338)
    }),
    _N_E = n.O()
}
]);
```

### To reproduce

There is no straight way to reproduce it as mentioned it is happening randomly.

### Version

I am using  "@markdoc/next.js": "^0.2.2", as it is next js project

### Additional context

Below is code of next.config.js

```
const withMarkdoc = require('@markdoc/next.js');

module.exports = withMarkdoc(/* config: https://markdoc.io/docs/nextjs#options */)({
  async rewrites() {
    return [
      {
        source: '/:any*',
        destination: '/',
      },
    ];
  },
  pageExtensions: ['js', 'jsx', 'ts', 'tsx', 'md', 'mdoc'],
  basePath: '/docs',
  compiler :{
     styledComponents: true,
  }
});
```

**Comment by mfix-stripe** [comment]
@Yashaswi-1998 can you share a repository that recreates this error? Thanks!

**Comment by maxblank-stripe** [comment]
Closing the issue due to no response.
