### ISSUE TITLE
Markdoc language server on a Next.js app

### ISSUE THREAD

**Issue by filiphric** [markdoc/markdoc#499]
### What happened?

I’ve been trying to set up VS Code Markdown extension, but I keep getting errors and can’t get it to work. I keep hitting the following message:

<img width="259" alt="Screenshot 2024-04-11 at 07 17 32" src="https://github.com/markdoc/markdoc/assets/23213553/c21bc544-094d-4e12-a177-27949544a523">

Here’s my `markdoc.config.json`
```json
[
  {
    "id": "docs",
    "path": "src/app",
    "schema": {
      "path": "src/markdoc/config.mjs",
      "type": "esm",
      "property": "default",
      "watch": true
    }
  }
]
```

The VS Code extenstion output is throwing following error:
```sh
TypeError: Cannot read properties of undefined (reading 'markdoc')
    at new Documents (/Users/filiphric/.vscode/extensions/stripe.markdoc-language-support-0.0.12/dist/client/server.js:27176:52)
    at /Users/filiphric/.vscode/extensions/stripe.markdoc-language-support-0.0.12/dist/client/server.js:27434:7
    at Array.map (<anonymous>)
    at server (/Users/filiphric/.vscode/extensions/stripe.markdoc-language-support-0.0.12/dist/client/server.js:27432:41)

Node.js v18.18.2
[Error - 07:17:51] Connection to server got closed. Server will not be restarted.
```

I’ve looked into the discussion threads but solutions mentioned there don’t seem to fix the problem for me. Maybe I’m overlooking something.

### To reproduce

[Here’s a link](https://github.com/replayio/docs/commit/b69b512d7d7e8e6ad598486c721bbba4e0e5be2a) to the repository 
Pull the latest changes from `new-docs` branch 

### Version

"@markdoc/markdoc": "^0.4.0",     "@markdoc/next.js": "^0.3.7",  Markdoc language support v0.0.12

### Additional context

I tried v0.0.11 of the extension which does not throw the error into the output console, but throws the same "Command 'Control the Markdoc language server' resulted in an error"

**Comment by louiss0** [comment]
I'm also dealing with a similar problem.

```
Node.js v18.18.2
[Info  - 12:39:07 PM] Connection to server got closed. Server will restart.
c:\Users\V. L. MULTISERVICE\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176
    this.tokenizer = new Markdoc4.Tokenizer(config.markdoc ?? {});
                                                   ^

TypeError: Cannot read properties of undefined (reading 'markdoc')
    at new Documents (c:\Users\V. L. MULTISERVICE\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176:52)
    at c:\Users\V. L. MULTISERVICE\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27434:7
    at Array.map (<anonymous>)
    at server (c:\Users\V. L. MULTISERVICE\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27432:41)

Node.js v18.18.2
[Error - 12:39:08 PM] Connection to server got closed. Server will not be restarted.
```

I'm using node v20.13.1 
Does that matter.

**Comment by filiphric** [comment]
Hey there! I’m assuming it is hard to prioritize this currently, and I don’t want to step on anybody’s toes, but if there’s a way I could help out, let me know. It would be a huge help for me to have this fixed.
