### ISSUE TITLE
Markdoc Language Server is not working

### ISSUE THREAD

**Issue by louiss0** [markdoc/markdoc#510]
### What happened?

I expected the Markdoc language server to give me suggestions on tags when working with Astro.
Instead I didn't get any information at all. 

### To reproduce

1. Open the repo.
2. Make sure the latest version of the markdoc language server is installed 
3. Install the latest dependencies

### Version

4.0

### Additional context

I'm using the `@astrojs/markdoc` extension with astro.

Here's proof that markdoc isn't working with Astro.

![Markdoc-LS-Malfunction-Proof](https://github.com/markdoc/markdoc/assets/29028601/9773b9b4-f7f5-42fb-92a8-12ca7291818f)

```sh
.
├── src/
│   └── content
├── markdoc.config.json
└── markdoc.config.mjs
```

**Comment by louiss0** [comment]
What is going on @segphault  Is this issue a priority?

**Comment by segphault** [comment]
Sorry for the delayed response, I must have missed this one. I'm having some trouble reproducing it — I'm using the dummy project you linked, and it appears to be working for me:

<img width="499" alt="image" src="https://github.com/markdoc/markdoc/assets/33037/811387d5-fe9e-427c-87de-b83d10b59e9c">

Do you have the dependencies installed in `node_modules`?

If you click the "Markdoc: <project name>" status bar item and then click the "show output" button in the dialog that pops up, it should show you the language server's output. Do you see any error messages in there that would suggest that it's failing to evaluate the schema?

**Comment by louiss0** [comment]
This is what I get when I try using version 0.0.13

```sh
c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176
    this.tokenizer = new Markdoc4.Tokenizer(config.markdoc ?? {});
                                                   ^

TypeError: Cannot read properties of undefined (reading 'markdoc')
    at new Documents (c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176:52)
    at c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27434:7
    at Array.map (<anonymous>)
    at server (c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27432:41)

Node.js v20.9.0
[Info  - 8:59:48 PM] Connection to server got closed. Server will restart.
c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176
    this.tokenizer = new Markdoc4.Tokenizer(config.markdoc ?? {});
                                                   ^

TypeError: Cannot read properties of undefined (reading 'markdoc')
    at new Documents (c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176:52)
    at c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27434:7
    at Array.map (<anonymous>)
    at server (c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27432:41)

Node.js v20.9.0
[Info  - 8:59:49 PM] Connection to server got closed. Server will restart.
c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176
    this.tokenizer = new Markdoc4.Tokenizer(config.markdoc ?? {});
                                                   ^

TypeError: Cannot read properties of undefined (reading 'markdoc')
    at new Documents (c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176:52)
    at c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27434:7
    at Array.map (<anonymous>)
    at server (c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27432:41)

Node.js v20.9.0
[Info  - 8:59:49 PM] Connection to server got closed. Server will restart.
c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176
    this.tokenizer = new Markdoc4.Tokenizer(config.markdoc ?? {});
                                                   ^

TypeError: Cannot read properties of undefined (reading 'markdoc')
    at new Documents (c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176:52)
    at c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27434:7
    at Array.map (<anonymous>)
    at server (c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27432:41)

Node.js v20.9.0
[Info  - 8:59:49 PM] Connection to server got closed. Server will restart.
c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176
    this.tokenizer = new Markdoc4.Tokenizer(config.markdoc ?? {});
                                                   ^

TypeError: Cannot read properties of undefined (reading 'markdoc')
    at new Documents (c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27176:52)
    at c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27434:7
    at Array.map (<anonymous>)
    at server (c:\Users\Venel Louis\.vscode\extensions\stripe.markdoc-language-support-0.0.12\dist\client\server.js:27432:41)

Node.js v20.9.0
[Error - 8:59:49 PM] Connection to server got closed. Server will not be restarted.

```

**Comment by louiss0** [comment]
I get nothing when it comes to 0.0.13 I get nothing.

**Comment by segphault** [comment]
With 0.0.13, if the statusbar item appears but there's nothing in the output, that means the language server is at least running. Could you try looking at the process list and see if it's there? On a Mac/Linux system, that would be something like `ps aux | grep markdoc`  and then you want to look for something in the output that looks like `stripe.markdoc-language-support-0.0.13/dist/client/server.js --node-ipc --clientProcessId=96476`. That would verify that the language server is running.

Do any other Markdoc features besides syntax highlighting work? Like does it show error highlighting on invalid tags? Do you see a "Partials" pane in the explorer sidebar when a Markdoc file has focus? Does it show "Markdoc" as the language on the right-hand side of the statusbar?

**Comment by segphault** [comment]
I've never previously tested the language server on Windows, Stripe uses macs exclusively and I develop on Linux at home. I just tried it on Windows 11 and I'm seeing the same behavior that you describe. Digging in a little bit, the language server and extension are definitely starting, the language server plugins are instantiating, several features like the partial pane work as expected, but validation is not running and features like partial peeking aren't working.

There's likely a Windows-specific issue somewhere. I can try to dig into it further over the weekend.

**Comment by louiss0** [comment]
> I've never previously tested the language server on Windows, Stripe uses macs exclusively and I develop on Linux at home. I just tried it on Windows 11 and I'm seeing the same behavior that you describe. Digging in a little bit, the language server and extension are definitely starting, the language server plugins are instantiating, several features like the partial pane work as expected, but validation is not running and features like partial peeking aren't working.
> 
> There's likely a Windows-specific issue somewhere. I can try to dig into it further over the weekend.

Windows OMG. I hope this can be fixed.

**Comment by louiss0** [comment]
Ok @segphault  did anything happen yet? 

I don't mean to bother you, but it has been 5 days.

**Comment by segphault** [comment]
I'm still working through this. There are honestly a bunch of platform-specific issues that are going to be painful to resolve.

- The `documentSelector` glob appears to behave differently on Windows than it does on other platforms — it's treating a `**` glob as though it is a single star instead of matching recursively. This means that the LSP is only trying to use features like validation and autocomplete on files that are one level underneath the content directory specified in the config.
- The ESM schema fails to import because when it encounters a path that starts with a Windows drive letter (e.g. `C:\`) it thinks that is the protocol. We'd need to have platform-specific logic there to normalize the path when it detects that the user is running on Windows.

There are probably more places where things are broken on Windows, but it's hard to tell without spending a lot more time. I'm really confused about the `documentSelector` glob issue, and I'm wondering if it is a bug in VSCode itself. I need to dig into the actual implementation of the glob parsing in order to understand what is going on there.

**Comment by louiss0** [comment]
I might have to switch to Linux. OMG Windows you are a pain

**Comment by louiss0** [comment]
Any updates?

**Comment by KingOfTac** [comment]
> * The ESM schema fails to import because when it encounters a path that starts with a Windows drive letter (e.g. `C:\`) it thinks that is the protocol. We'd need to have platform-specific logic there to normalize the path when it detects that the user is running on Windows.

I ran into this exact issue in another project. The solution was to import `pathToFileUrl` from the node.js url module and pass the file path to it before trying to import it.

Something like: `const importedModule = import(pathToFileUrl(filePath).href);` if I remember correctly. This works cross platform so no need for platform specific logic.

**Comment by louiss0** [comment]
Wow it has been months and yet there is no solution in sight!
