### ISSUE TITLE
Crash with particular title input

### ISSUE THREAD

**Issue by cyrusboadway** [markdoc/markdoc#6]
### What happened?

Providing specific content related to the title crashes the application: "Application error: a client-side exception has occurred (see the browser console for more information)."

```
framework-5f4595e5518b5600.js:1 TypeError: Cannot read properties of null (reading 'title')
    at 605040ef-5bf360b804c2c400.js:1:117210
    at Array.reduce (<anonymous>)
    at Se.resolve (605040ef-5bf360b804c2c400.js:1:117191)
    at Te (605040ef-5bf360b804c2c400.js:1:117674)
    at Te (605040ef-5bf360b804c2c400.js:1:117792)
    at rt.resolve (605040ef-5bf360b804c2c400.js:1:123029)
    at 605040ef-5bf360b804c2c400.js:1:123005
    at Array.map (<anonymous>)
    at rt.resolve (605040ef-5bf360b804c2c400.js:1:122995)
    at 605040ef-5bf360b804c2c400.js:1:123005
```

### To reproduce

The following content crashes the demo app:

```
---
#
---
```

(i.e. deleting `title: What is Markdoc?` and replacing it with `#`)

### Version

Unsure, but whichever the demo page is using.

**Comment by mfix-stripe** [comment]
Thanks @cyrusboadway. Fixed here: https://github.com/markdoc/docs/commit/e1fc963b0150b41f82ec78920301f42b5d09f79b

**Comment by cyrusboadway** [comment]
👍
